name: Python application

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt

    - name: Run lint, tests, and coverage (100% required)
      run: |
        source .venv/bin/activate
        export PYTHONPATH=.
        pytest --pylint --cov=src --cov-report=term-missing --cov-fail-under=100
